version: '3.7'

# WARNING: PUPPET AGENT MUST CHECK IN AT LEAST ONCE FOR THIS TO WORK

services:

  puppetboard:
    image: camptocamp/puppetboard:3.0.0
    ports:
      - 8000:80

  puppet-agent:
    image: puppet/puppet-agent-alpine:7.5.0

networks:
  default:
    external:
      name: pupperware_default
