version: '3.7'

# WARNING: PUPPET AGENT MUST CHECK IN AT LEAST ONCE FOR THIS TO WORK

services:

  puppetboard:
    image: camptocamp/puppetboard:latest
    ports:
      - 8000:80

networks:
  default:
    external:
      name: pupperware_default
