FROM centos:centos7
RUN yum install -y https://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm
RUN yum install -y puppet-agent \
                    less \
                    rsyslog \
                    crontabs
