---
- hosts: server
  tasks:
    - name: Install packages
      raw: |
          yum install -y https://yum.puppet.com/puppet6/puppet-release-el-7.noarch.rpm
          yum install -y puppet-agent-6.19.1
    - name: facts.txt
      copy:
        dest: "/opt/puppetlabs/facter/facts.d/facts.txt"
        content: |
          puppetserver=someserver
          environment=someenv
          role=somerole
    - name: puppet.conf
      copy:
        dest: "/etc/puppetlabs/puppet/puppet.conf"
        content: |
          [agent]
          server      = someserver
          environment = someenv
          certname    = somerole-$(head /dev/urandom | tr -dc a-z0-9 | head -c 13 ; echo '')
          runinterval = 30m
