---
- hosts: server
  remote_user: osboxes
  become: yes
  tasks:
    - name: Install packages
      raw: |
          yum install -y https://yum.puppet.com/puppet6/puppet-release-el-7.noarch.rpm
          yum install -y puppet-agent-6.19.1
