# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize [
      "modifyvm", :id,
      "--natdnshostresolver1", "on",
    ]
  end
  config.vm.provider "libvirt" do |v|
    v.random_hostname = true
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.provision "shell",
    inline: """
    yum install -y https://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm
    yum install -y puppet-agent
    /opt/puppetlabs/bin/puppet agent -t --noop --environment master
    """
end
