# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SHELL
    if ! grep -q "puppet" /etc/hosts; then
        echo "192.168.1.7 puppet" >> /etc/hosts;
    fi
    yum install -y https://yum.puppet.com/puppet6/puppet-release-el-7.noarch.rpm
    yum install -y puppet-agent-6.18.0
    echo virtual=kvm > /opt/puppetlabs/facter/facts.d/facts.txt
    rm -r /etc/puppetlabs/puppet/ssl
    CERTNAME=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)
    /opt/puppetlabs/bin/puppet agent -t --certname $CERTNAME --environment master
SHELL

end
